/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Account": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AdminDiscordIds": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MeleeClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MeleeClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Placement": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Player": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Tournament": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}

import "sst"
export {}